name: CI

on: push

jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies (linux)
        run: sudo apt install ninja-build
        if: matrix.os == 'ubuntu-latest'

      - name: Install Ninja (windows)
        run: choco install ninja
        if: matrix.os == 'windows-latest'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'

      - uses: ilammy/msvc-dev-cmd@v1
      
      - uses: actions/checkout@v3  # Check out the sources for RMP_LosRios
      
      # Debugging Step: List current directory
      - name: List current directory after RMP_LosRios checkout
        run: ls -alh

      # Clone the UnitTestRMP repository (TestClasses)
      - name: Checkout UnitTestRMP (TestClasses) repository
        run: |
          git clone https://github.com/Katz100/UnitTestRMP.git TestClasses  # Cloning the TestClasses repository

      # Debugging Step: List directories after cloning UnitTestRMP
      - name: List directories after cloning UnitTestRMP
        run: ls -alh

      # Build RMP_LosRios project
      - name: Build RMP_LosRios
        run: |
          cmake -S . -B build -G "Ninja Multi-Config" && \
          cmake --build build --config Debug

      # Navigate to the cloned TestClasses directory and build it
      - name: Build TestClasses
        run: |
          cd TestClasses/TestClasses  # Ensure we're in the correct directory
          cmake -S . -B build -G "Ninja Multi-Config" && \
          cmake --build build --config Debug
      
      # Run the tests from TestClasses
      - name: Run Tests
        run: |
          cd TestClasses/build
          ctest --output-on-failure
